### ISSUE TITLE
about the password of the host login page

### ISSUE THREAD

**Issue by AICrazyyy** [awtrix/AWTRIX2.0-Docs#3]
Hello, I downloaded the stable version of awtrix.jar. When I log in to the webpage [IP: 7000], I am required to enter the password, but I don't know what the password is.

Could you please tell me where to find the password?
![image](https://user-images.githubusercontent.com/17903073/76399812-3dcaf700-63ba-11ea-88f0-06780d0a277b.png)

**Comment by Blueforcer** [comment]
its awtrix, like described in the Documentation

**Comment by AICrazyyy** [comment]
thank you, it's allready sloved.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Stephan Mühl"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月15日(星期天) 凌晨5:25
收件人:&nbsp;"awtrix/AWTRIX2.0-Docs_Beta"<AWTRIX2.0-Docs_Beta@noreply.github.com&gt;;
抄送:&nbsp;"zhongzhiguo"<867959943@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [awtrix/AWTRIX2.0-Docs_Beta] about the password of the host login page (#3)





 
its awtrix, like described in the Documentation
